version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
  db:
    image: mysql:8.3
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - NYSQL_USER=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
